const commonCriteria = ["Control of the incident", "Effective command"];
const infoGatheringAll = [
    "Confirmation of previous actions", "Confirmation of hazards", "Confirmation of risk assessments",
    "Confirmation of previous role assignments", "Determine suitability and sufficiency of resources",
    "Determine involvement of other agencies", "Information gathering"
];

export const timelineData = [
  { id: 'front-of-house', title: 'FRONT OF HOUSE', time: '0.00', length: 0, type: 'node', detail: ['CANDIDATE IN POD 1', 'RECEIVING BREIF ABOUT PROCESS'], criteria: [...commonCriteria] },
  { id: 'mobilisation', title: 'MOBILISATION', time: '0.00', length: 0, type: 'node', detail: ['CANDIDATE IN POD 1', 'RECEIVING MOBILISATION DETAILS', 'CALL TO CONTROL', 'BOOK ATTENDANCE AT INCIDENT'], criteria: [...commonCriteria, ...infoGatheringAll] },
  { id: 'handover', title: 'HANDOVER', time: '15:22', length: 10, type: 'node', detail: ['IC2 HANDOVER / CONSOLIDATION', 'HEAVY ON BA', 'CANDIDATE ON COMMAND UNIT', '10 MINUTES ALLOWED TO HANDOVER'], criteria: [...commonCriteria, ...infoGatheringAll, "Confirm priority actions and objectives", "Action planning", "Assuming command", "Communication with people", "Transmitting tactical mode"] },
  { id: 'inject-1', title: 'INJECT 1', time: '15:32', length: 3, type: 'node', detail: ['UPDATE FROM SECTOR 1', 'UPDATE ON SYSTEMATIC SEARCH', '4 X BA CREWS – LEFT AND RIGHT HAND WALL', 'LIST UNIT AREAS SEARCHED'], criteria: [...commonCriteria, "Resource evaluation", "Risk evaluation", "Action planning", "Safe systems of work", "Actively monitor the progress of activity against your plan"] },
  { id: 'inject-2', title: 'INJECT 2', time: '15:35', length: 5, type: 'node', detail: ['RP - STORE MANAGER', 'TRIED CALLED ‘MR SHORT’', 'NO ANSWER – RANG OFF', 'WILL KEEP TRYING', 'DELIVER CUSTOMER LIST (MR SHORTS UNIT NO.)'], rolePlayers: ['Store Manager'], criteria: [...commonCriteria, ...infoGatheringAll, "Resource evaluation", "Risk evaluation", "Use of command support", "Communication with people"] },
  { id: 'inject-2-branch', type: 'branch', options: [
      { id: 'inject-2-opt-1', title: 'OPTION 1', type: 'node', branchLabel: 'Inject 2', detail: ['CANDIDATE ACTION:', 'DOES NOT COMMIT TO THE 1ST FLOOR'], criteria: [...commonCriteria] },
      { id: 'inject-2-opt-2', title: 'OPTION 2', type: 'node', branchLabel: 'Inject 2', detail: ['CANDIDATE ACTION:', 'DOES COMMIT TO THE 1ST FLOOR'], criteria: [...commonCriteria] }
  ]},
  { id: 'inject-3', title: 'INJECT 3', time: '15:40', length: 5, type: 'node', detail: ['SC HUNT RETURNS', 'PRESS STATEMENT DONE', 'READY FOR RE-TASKING', 'NO OTHER TAGS'], rolePlayers: ['SC Hunt'], criteria: [...commonCriteria, "Delegating spans of control", "Communication with people", "Transmitting tactical mode"] },
  { id: 'inject-4', title: 'INJECT 4', time: '15:45', length: 3, type: 'node', detail: ['SECTOR 1 UPDATE', 'FIRE LOCATED', 'UNIT 2-S-7', '1ST FLOOR – 1-D-2 LOCATED'], criteria: [...commonCriteria, "Risk evaluation"] },
  { id: 'inject-5', title: 'INJECT 5', time: '15:48', length: 7, type: 'node', detail: ['SC PETIT', 'COMPLETED ARA'], rolePlayers: ['SC Petit'], criteria: [...commonCriteria, "Delegating spans of control", "Use of command support"] },
  { id: 'inject-6', title: 'INJECT 6', time: '15:55', length: 5, type: 'node', detail: ['SC WIGHT', 'AS PER PDA', 'HOLDS BMA TAG (NO CURRENT ISSUES WITH WATER)'], rolePlayers: ['SC Wight'], criteria: [...commonCriteria, "Delegating spans of control", "Communication with people", "Transmitting tactical mode"] },
  { id: 'inject-7', title: 'INJECT 7', time: '16:00', length: 5, type: 'node', detail: ['SECTOR 3', 'SMOKE SEEN FROM ROOF', 'MOVING TOWARDS THE PYLON', 'LIGHT GREY', 'DRONE FOOTAGE AVAILABLE'], criteria: [...commonCriteria, "Resource evaluation", "Risk evaluation", "Review of risk assessment"] },
  { id: 'inject-8', title: 'INJECT 8', time: '16:05', length: 3, type: 'node', detail: ['SECTOR 1 – UPDATE', 'DEEP SEATED FIRE', 'HEAVY FIRE LOADING', 'HOT HARD WORK FOR BA', 'MAM PROMPT – 10 MINUTES'], criteria: [...commonCriteria, "Obtained professional advice to help evaluate", "Evaluation of impact on the organisation and others", "Communication with people"] },
  { id: 'inject-9', title: 'INJECT 9', time: '16:08', length: 7, type: 'node', detail: ['SC BREEN SCRIPT'], rolePlayers: ['SC Breen'], criteria: [...commonCriteria, "Resource evaluation", "Risk evaluation", "Action planning", "Safe systems of work", "Actively monitor the progress of activity against your plan"] },
  { id: 'inject-10', title: 'INJECT 10', time: '16:15', length: 15, type: 'node', detail: ['MAM', 'POLICE', 'RP – STORE MANAGER', 'UKPN'], rolePlayers: ['Police', 'Store Manager', 'UKPN'], criteria: [...commonCriteria, "Resource evaluation", "Risk evaluation", "Review of risk assessment", "Actively monitor the progress of activity against your plan"] },
  { id: 'inject-11-branch', type: 'branch', linkedId: 'inject-11-choice', options: [
      { id: 'inject-11-opt-1', title: 'INJECT 11 (Op 1)', time: '16:30', length: 3, type: 'node', branchLabel: 'Inject 11', detail: ['EXTERNAL FF TACTICS', 'SECTOR 1 UPDATE', 'AFA ACTUATING ON 1ST FLOOR – SEEN FROM CONTROL PANEL', 'EXTERNAL MEASURES IN PLACE AS DIRECTED', 'DRONE FOOTAGE UPDATED', 'SECTOR 3', 'BLACK SMOKE GOING NEAR PYLON', 'NOT ARCING'], criteria: [...commonCriteria] },
      { id: 'inject-11-opt-2', title: 'INJECT 11 (Op 2)', time: '16:30', length: 3, type: 'node', branchLabel: 'Inject 11', detail: ['INTERNAL FF TACTICS', 'SECTOR 1 UPDATE', 'AFA ACTUATING ON 1ST FLOOR – SEEN FROM CONTROL PANEL', 'INTERNAL OPERATIONS – STEADY PROGRESS', 'SECTOR 3 UPDATE', 'LIGHT SMOKE STILL GOING TOWADS PYLON', 'NOT ARCING'], criteria: [...commonCriteria] }
  ]},
  { id: 'inject-12', title: 'INJECT 12', time: '16:33', length: 2, type: 'node', detail: ['STORE MANAGER UPDATE', 'MR SHORT IS NOW ACCOUNTED FOR', 'LOCATED AT HOME'], criteria: [...commonCriteria, "Update of tactical mode", "Review of risk assessment"] },
  { id: 'inject-13-branch', type: 'branch', linkedId: 'inject-13-choice', options: [
      { id: 'inject-13-opt-1', title: 'INJECT 13 (Op 1)', time: '16:35', length: 5, type: 'node', branchLabel: 'Inject 13', detail: ['EXTERNAL FF TACTICS', 'SECTOR 3 UPDATE', 'THICK BLACK SMOKE NOW SEEN COMING FROM ROOF', 'DRONE FOOTAGE UPDATED'], criteria: [...commonCriteria, "Resource evaluation", "Risk evaluation", "Review of risk assessment", "Actively monitor the progress of activity against your plan"] },
      { id: 'inject-13-opt-2', title: 'INJECT 13 (Op 2)', time: '16:35', length: 5, type: 'node', branchLabel: 'Inject 13', detail: ['INTERNAL FF TACTICS', 'SECTOR 1 UPDATE', 'FIRE CONFIRMED ON 1ST FLOOR', 'DIRECTLY BELOW FIRE ON 2ND FLOOR', 'CREWS STILL FIREFIGHTING ON 2ND FLOOR ABOVE FIRE ON 1ST', 'COMMIT CREWS WITH 45MM JETS'], criteria: [...commonCriteria, "Resource evaluation", "Risk evaluation", "Review of risk assessment", "Actively monitor the progress of activity against your plan"] }
  ]},
  { id: 'inject-14', title: 'INJECT 14', time: '16:40', length: 10, type: 'node', detail: ['HANDOVER', 'CANDIDATE TO HANDOVER COMMAND TO DAC'], rolePlayers: ['DAC'], criteria: [...commonCriteria, "Obtained professional advice to help evaluate", "Evaluation of impact on the organisation and others", "Action planning", "Communication with people"] },
  { id: 'end-of-exercise', title: 'END', time: '16:50', length: 0, type: 'node', detail: ['END OF EXERCISE', 'CANDIDATE TO BE ASCORTED OFF SITE AND AWAIT FEEDBACK'], criteria: [...commonCriteria] }
];
