const commonCriteria = ["Control of the incident", "Effective command"];
const infoGatheringAll = [
    "Confirmation of previous actions", "Confirmation of hazards", "Confirmation of risk assessments",
    "Confirmation of previous role assignments", "Determine suitability and sufficiency of resources",
    "Determine involvement of other agencies", "Information gathering"
];

export const timelineData = [
  { id: 'front-of-house', title: 'FRONT OF HOUSE', time: '0.00', type: 'node', detail: ['CANDIDATE IN POD 1', 'RECEIVING BREIF ABOUT PROCESS'], criteria: [...commonCriteria] },
  { id: 'mobilisation', title: 'MOBILISATION', time: '0.00', type: 'node', detail: ['CANDIDATE IN POD 1', 'RECEIVING MOBILISATION DETAILS', 'CALL TO CONTROL', 'BOOK ATTENDANCE AT INCIDENT'], criteria: [...commonCriteria, ...infoGatheringAll] },
  { id: 'handover', title: 'HANDOVER', time: '15:22', type: 'node', detail: ['IC2 HANDOVER', 'CANDIDATE ON COMMAND UNIT', '10 MINUTES ALLOWED TO CONSOLIDATE AND ENGAGE COMMAND SUPPORT'], criteria: [...commonCriteria, ...infoGatheringAll, "Confirm priority actions and objectives", "Action planning", "Assuming command", "Communication with people", "Transmitting tactical mode"] },
  { id: 'inject-1', title: 'INJECT 1', time: '15:30', type: 'node', detail: ['UPDATE FROM S1', 'UPDATE ON SYSTEMATIC SEARCH', '4 X BA CREWS – LEFT AND RIGHT HAND WALL', 'LIST UNIT AREAS SEARCHED'], criteria: [...commonCriteria, "Resource evaluation", "Risk evaluation", "Action planning", "Safe systems of work", "Actively monitor the progress of activity against your plan"] },
  { id: 'inject-2', title: 'INJECT 2', time: '15:32', type: 'node', detail: ['RP - STORE MANAGER', 'DELIVER PLANS', 'UPDATE ON CUSTOMERS', 'TRIGGER FOR PERSONS REPORTED'], rolePlayers: ['Store Manager'], criteria: [...commonCriteria, ...infoGatheringAll, "Resource evaluation", "Risk evaluation", "Use of command support", "Communication with people"] },
  { id: 'inject-2-branch', type: 'branch', options: [
      { id: 'inject-2-opt-1', title: 'OPTION 1', type: 'node', branchLabel: 'Inject 2', detail: ['CANDIDATE ACTION:', 'DOES NOT COMMIT TO THE 1ST FLOOR'], criteria: [...commonCriteria] },
      { id: 'inject-2-opt-2', title: 'OPTION 2', type: 'node', branchLabel: 'Inject 2', detail: ['CANDIDATE ACTION:', 'DOES COMMIT TO THE 1ST FLOOR'], criteria: [...commonCriteria] }
  ]},
  { id: 'inject-3', title: 'INJECT 3', time: '15:40', type: 'node', detail: ['SC HUNT RETURNS', 'PRESS STATEMENT DONE', 'READY FOR RE-TASKING', 'NO OTHER TAGS'], rolePlayers: ['SC Hunt'], criteria: [...commonCriteria, "Delegating spans of control", "Communication with people", "Transmitting tactical mode"] },
  { id: 'inject-4', title: 'INJECT 4', time: '15:45', type: 'node', detail: ['RP AT THE WINDOW', 'TRIED CALLED ‘MR SHORT’', 'NO ANSWER – RANG OFF', 'WILL KEEP TYRING'], criteria: [...commonCriteria, "Risk evaluation"] },
  { id: 'inject-5', title: 'INJECT 5', time: '15:48', type: 'node', detail: ['VEHICLE MOVEMENTS', 'ON COMING APPIANCES STRUGGLING TO PARK', 'VEHICLE MOVEMENTS FROM THE BUSINESS PARK IMPACTING SAFETY'], criteria: [...commonCriteria, "Delegating spans of control", "Use of command support"] },
  { id: 'inject-5-branch', type: 'branch', options: [
      { id: 'inject-5-opt-1', title: 'OPTION 1', type: 'node', branchLabel: 'Inject 5', detail: ['CANDIDATE ACTION:', 'DOES NOT IMPLIMENT MARSHALLING'], criteria: [...commonCriteria] },
      { id: 'inject-5-opt-2', title: 'OPTION 2', type: 'node', branchLabel: 'Inject 5', detail: ['CANDIDATE ACTION:', 'DOES IMPLIMENT MARSHALLING'], criteria: [...commonCriteria] }
  ]},
  { id: 'inject-6', title: 'INJECT 6', time: '15:55', type: 'node', detail: ['SC ATTANDANCE', 'AS PER PDA', 'HOLDS BMA TAG (NO CURRENT ISSUES WITH WATER)'], rolePlayers: ['SC Petit'], criteria: [...commonCriteria, "Delegating spans of control", "Communication with people", "Transmitting tactical mode"] },
  { id: 'inject-7', title: 'INJECT 7', time: '16:00', type: 'node', detail: ['SECTOR 3 UPDATE', 'SMOKE SEEN FROM ROOF', 'MOVING TOWARDS THE PYLON', 'LIGHT GREY'], criteria: [...commonCriteria, "Resource evaluation", "Risk evaluation", "Review of risk assessment"] },
  { id: 'inject-8', title: 'INJECT 8', time: '16:02', type: 'node', detail: ['POLICE INJECT', 'CONCERNS FOR BUSINESS PARK ACTIVITY', 'PHARMASUITCAL BUS. MUST HAVE ACCESS', 'INJECT 5 OPTIONS CONCLUDED'], rolePlayers: ['Police'], criteria: [...commonCriteria, "Obtained professional advice to help evaluate", "Evaluation of impact on the organisation and others", "Communication with people"] },
  { id: 'inject-9', title: 'INJECT 9', time: '16:10', type: 'node', detail: ['SECTOR 1 UPDATE', 'UPDATE TO CONCIDER INJECT 2 OPTIONS', '2ND FLOOR SEARCH PATTERN (75% COMPLETE)'], criteria: [...commonCriteria, "Resource evaluation", "Risk evaluation", "Action planning", "Safe systems of work", "Actively monitor the progress of activity against your plan"] },
  { id: 'inject-10', title: 'INJECT 10', time: '16:12', type: 'node', detail: ['DRONE FOOTAGE', 'DISPLAYED ON CU SCREEN', 'LIGHT SMOKE SEEN FROM ROOF'], criteria: [...commonCriteria, "Resource evaluation", "Risk evaluation", "Review of risk assessment", "Actively monitor the progress of activity against your plan"] },
  { id: 'inject-11', title: 'INJECT 11', time: '16:15', type: 'node', detail: ['SFSO AND UKPN IN ATTENDANCE', 'SEE SCRIPTS', 'HAZARDS OUTLINED BY SFSO AND UKPN', 'CONSEQUENCES OUTLINED BY UKPN'], rolePlayers: ['SFSO', 'UKPN'], criteria: [...commonCriteria, "Obtained professional advice to help evaluate", "Evaluation of impact on the organisation and others", "Action planning", "Safe systems of work", "Crisis management", "Communication with people", "Transmitting tactical mode", "Update of tactical mode", "Review of risk assessment"] },
  { id: 'inject-11a', title: 'INJECT 11a', time: '16:18', type: 'node', detail: ['UPDATE FROM SECTOR 1 - DELIVERED DURING INJECT 11', 'FIRE LOCATED ON 2ND FLOOR', 'UNIT 2-S-7', 'CREWS APPLYING WATER'], criteria: [...commonCriteria] },
  { id: 'inject-11-branch', type: 'branch', linkedId: 'inject-11-choice', options: [
      { id: 'inject-11-opt-1', title: 'OPTION 1', type: 'node', branchLabel: 'Inject 11', detail: ['CANDIDATE ACTION:', 'TACTICAL WITHDAWL FROM BUILDING'], criteria: [...commonCriteria] },
      { id: 'inject-11-opt-2', title: 'OPTION 2', type: 'node', branchLabel: 'Inject 11', detail: ['CANDIDATE ACTION:', 'CONTINUE WITH INTERNAL OPERATIONS'], criteria: [...commonCriteria] }
  ]},
  { id: 'inject-12', title: 'INJECT 12', time: '16:25', type: 'node', detail: ['SECTOR SAFETY UPDATE', 'ARA RETURNED', 'BESPOKE TO INJECT 11 OPTIONS'], criteria: [...commonCriteria, "Update of tactical mode", "Review of risk assessment"] },
  { id: 'inject-13-branch', type: 'conditional', dependsOn: 'inject-11-choice', options: {
      'inject-11-opt-1': { id: 'inject-13-opt1', title: 'INJECT 13 (Op 1)', time: '16:30', type: 'node', detail: ['SECTOR 1 UPDATE', 'AFA ACTUATING ON 1ST FLOOR – SEEN FROM CONTROL PANEL', 'EXTRENAL MEASURES IN PLACE AS DIRECTED', 'DRONE FOOTAGE UPDATED', 'SECTOR 3', 'BLACK SMOKE GOING NEAR PYLON', 'NOT ARCHING'], criteria: [...commonCriteria, "Resource evaluation", "Risk evaluation", "Review of risk assessment", "Actively monitor the progress of activity against your plan"] },
      'inject-11-opt-2': { id: 'inject-13-opt2', title: 'INJECT 13 (Op 2)', time: '16:30', type: 'node', detail: ['SECTOR 1 UPDATE', 'AFA ACTUATING ON 1ST FLOOR – SEEN FROM CONTROL PANEL', 'INTERNAL OPERATIONS – STEADY PROGRESS', 'AERIAL APPLIANCE SETUP (IF REQ.)', 'DRONE FOOTAGE UPDATED – WITH OR WITHOUT AERIAL', 'SECTOR 3 UPDATE', 'LIGHT SMOKE STILL GOING TOWADS PYLON', 'NOT ARCHING'], criteria: [...commonCriteria, "Resource evaluation", "Risk evaluation", "Review of risk assessment", "Actively monitor the progress of activity against your plan"] }
  }},
  { id: 'inject-14', title: 'INJECT 14', time: '16:35', type: 'node', detail: ['MAM', 'POLICE', 'RP – STORE MANAGER', 'UKPN'], rolePlayers: ['Police', 'Store Manager', 'UKPN'], criteria: [...commonCriteria, "Obtained professional advice to help evaluate", "Evaluation of impact on the organisation and others", "Action planning", "Communication with people"] },
  { id: 'inject-15-branch', type: 'conditional', dependsOn: 'inject-11-choice', options: {
      'inject-11-opt-1': { id: 'inject-15-opt1', title: 'INJECT 15 (Op 1)', time: '16:45', type: 'node', detail: ['SECTOR 3 UPDATE', 'THICK BLACK SMOKE NOW SEEN COMING FROM ROOF', 'DRONE FOOTAGE UPDATED'], criteria: [...commonCriteria, "Resource evaluation", "Risk evaluation", "Action planning", "Safe systems of work", "Crisis management", "Actively monitor the progress of activity against your plan"] },
      'inject-11-opt-2': { id: 'inject-15-opt2', title: 'INJECT 15 (Op 2)', time: '16:45', type: 'node', detail: ['SECTOR 1 UPDATE', 'FIRE CONFIRMED ON 1ST FLOOR', 'DIRECTLY BELOW FIRE ON 2ND FLOOR', 'CREWS STILL FIREFIGHTING ON 2ND FLOOR ABOVE FIRE ON 1ST'], criteria: [...commonCriteria, "Resource evaluation", "Risk evaluation", "Action planning", "Safe systems of work", "Crisis management", "Actively monitor the progress of activity against your plan"] }
  }},
  { id: 'inject-16', title: 'INJECT 16', time: '16:50', type: 'node', detail: ['HANDOVER', 'CANDIDATE TO HANDOVER COMMAND TO DAC'], criteria: [...commonCriteria, "Communication with people", "Transmitting tactical mode", "Senior officer briefing"] },
  { id: 'end-of-exercise', title: 'END', time: '16:55', type: 'node', detail: ['END OF EXERCISE', 'CANDIDATE TO BE ASCORTED OFF SITE AND AWAIT FEEDBACK'], criteria: [...commonCriteria] }
];
